### ISSUE TITLE
Compatibility with Drupal 8.6

### ISSUE THREAD

**Issue by pfrenssen** [ec-europa/rdf_entity#58]
We are currently experiencing some failures with the upcoming Drupal 8.6. We should fix these problems and ensure to get passing tests before 8.6.0 is released. This is currently scheduled for September.

- [x] #53 Database connection class not found in Drupal 8.6.x
- [x] #54 Configuration name does not match ID error on Drupal 8.6.x
- [x] #57 Enable testing on Drupal 8.6.x
- [x] Remove the `allow_failures` section from `.travis.yml` once we get a green test on 8.6.x.

**Comment by claudiu-cristea** [comment]
The new release `alpha10` is Drupal 8.6.x compatible.
